name: Cleanup Artifacts (Master Only)

on:
  schedule:
    - cron: '59 23 * * *'  # Every day at 11:59 PM UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest successful run for master
        id: latest_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "master",
              status: "success",
              per_page: 1
            });
            if (runs.data.workflow_runs.length > 0) {
              core.setOutput("run_id", runs.data.workflow_runs[0].id);
            } else {
              core.setOutput("run_id", "");
            }

      - name: Delete artifacts except for latest successful master run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = process.env.RUN_ID;
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            for (const artifact of artifacts.data.artifacts) {
              if (runId && String(artifact.workflow_run.id) !== String(runId)) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
              }
            }
        env:
          RUN_ID: ${{ steps.latest_run.outputs.run_id }}