name: Instant Cleanup 

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Get current storage usage
        id: before
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Only MB, no bytes shown [CHANGED]
            let artifactBytes = 0;
            let page = 1;
            while (true) {
              const { data } = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page
              });
              if (data.artifacts.length === 0) break;
              for (const artifact of data.artifacts) {
                artifactBytes += artifact.size_in_bytes;
              }
              page++;
            }
            const artifactMB = (artifactBytes / (1024 * 1024)).toFixed(2); // [CHANGED]
            core.info(`Current artifact storage used: ${artifactMB} MB`); // [CHANGED]
            core.setOutput('artifact_storage_mbs', artifactMB); // [CHANGED]

      - name: List and delete all artifacts
        id: cleanup
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Only MB, no bytes shown [CHANGED]
            let deletedCount = 0;
            let freedSpace = 0;
            let deleteLogs = [];
            let page = 1;
            while (true) {
              const { data } = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page
              });
              if (data.artifacts.length === 0) break;
              for (const artifact of data.artifacts) {
                try {
                  await github.rest.actions.deleteArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: artifact.id
                  });
                  deletedCount++;
                  freedSpace += artifact.size_in_bytes;
                  // Show MB per artifact [CHANGED]
                  const artifactMB = (artifact.size_in_bytes / (1024 * 1024)).toFixed(2);
                  deleteLogs.push(`Deleted: ${artifact.name} (ID: ${artifact.id}, Size: ${artifactMB} MB)`); // [CHANGED]
                } catch (e) {
                  deleteLogs.push(`Failed to delete: ${artifact.name} (ID: ${artifact.id}) - ${e.message}`);
                }
              }
              page++;
            }
            const freedMB = (freedSpace / (1024 * 1024)).toFixed(2); // [CHANGED]
            core.setOutput('deleted_count', deletedCount);
            core.setOutput('freed_space_mbs', freedMB); // [CHANGED]
            core.setOutput('delete_logs', deleteLogs.join('\n'));

      - name: Log artifact deletion details
        run: |
          echo "${{ steps.cleanup.outputs.delete_logs }}"
          echo "Total artifacts deleted: ${{ steps.cleanup.outputs.deleted_count }}"
          echo "Total space freed: ${{ steps.cleanup.outputs.freed_space_mbs }} MB" # [CHANGED]

      - name: Re-check storage usage after cleanup
        id: after
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Only MB, no bytes shown [CHANGED]
            let artifactBytes = 0;
            let page = 1;
            while (true) {
              const { data } = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page
              });
              if (data.artifacts.length === 0) break;
              for (const artifact of data.artifacts) {
                artifactBytes += artifact.size_in_bytes;
              }
              page++;
            }
            const artifactMB = (artifactBytes / (1024 * 1024)).toFixed(2); // [CHANGED]
            core.info(`Current artifact storage used: ${artifactMB} MB`); // [CHANGED]
            core.setOutput('artifact_storage_mbs', artifactMB); // [CHANGED]

      - name: Final cleanup summary
        run: |
          echo "Before cleanup: ${{ steps.before.outputs.artifact_storage_mbs }} MB" # [CHANGED]
          echo "After cleanup: ${{ steps.after.outputs.artifact_storage_mbs }} MB" # [CHANGED]
          echo "Space freed: ${{ steps.cleanup.outputs.freed_space_mbs }} MB" # [CHANGED]
